# Stubs for jsonschema.cli (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

parser: Any

def parse_args(args: Any): ...
def main(args: Any = ...) -> None: ...
def run(arguments: Any, stdout: Any = ..., stderr: Any = ...): ...
