# Stubs for jsonschema.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from itertools import izip as zip
from typing import Any

PY3: Any
zip = zip
str_types: Any
int_types: Any
iteritems: Any
str_types = basestring

def urlsplit(url: Any): ...
def urldefrag(url: Any): ...
